### PR TITLE
Fix empty nested embeddable

### PR DESCRIPTION
**Pull request by BoShurik**
Sorry :(

And tag please, as uploader-bundle related on this library

### CODE REVIEW

**Comment by BoShurik** [comment]
Don't merge, looks like there are still some bugs...

**Comment by BoShurik** [comment]
Ok. It was bug in the bundle (https://github.com/atom-php/uploader-bundle/pull/7/commits)

**Comment by BoShurik** [comment]
ping @atom-azimov

**Comment by atom-azimov** [comment]
Okay, sorry for long answer. I checked it out.
It works perfectly. :+1:

**Pull request merged**
